### PR TITLE
Remove unnecessary dependencies from Gemfiles

### PR DESCRIPTION
**Pull request by bmarkons**
I think we should keep our Gemfiles up to date for running latest Rails and Sequel versions.

Any additional setup for earlier versions we can customize in docker runner script.

### CODE REVIEW

**Comment by tgxworld** [comment]
Hmm I'm not sure if this should be the responsibility of the docker runner script. Any reason why you'll like to move it there?

**Comment by bmarkons** [comment]
I had in mind doing something like this for customizing Gemfile for lower versions of Rails: 
https://github.com/ruby-bench/ruby-bench-docker/blob/master/rails/master/runner#L39

What do you think?

**Comment by tgxworld** [comment]
Ah we definitely want that our of the runner. My belief is that gem versions should be managed in the Gemfile. The runner script's sole responsibility is to just run the benchmarks.

**Comment by bmarkons** [comment]
Fair enough, I am looking forward to move it out from runner :) closing this :no_entry:

**Pull request closed without merging**
