### PR TITLE
Add basic bundler suite

### PR DESCRIPTION
**Pull request by segiddins**
\c @indirect

### CODE REVIEW

**Comment by indirect** [comment]
holy hell, these gemfiles! :astonished: 

also yesssssssssssssssssssssssssssssssssssssssssssssssssssssssss

**Comment by SamSaffron** [comment]
@tgxworld what is up with this, can we get it merged ? :heart:

**Comment by tgxworld** [comment]
Looks good to me! Thank you @segiddins and @indirect  :smile_cat:  I'll get the results posted up on RubyBench soon! :smile:

**Comment by segiddins** [comment]
:heart: thanks so much for the help :)

**Pull request merged**
