### PR TITLE
Simplify requests in scaffold benchmarks

### PR DESCRIPTION
**Pull request by kirs**
@prathamesh-sonpatki @tgxworld

### CODE REVIEW

**Comment by tgxworld** [comment]
@kirs This is on my list. Just that the Rails benchmarks are broken at the moment due to bundler issues so I'm waiting to fix that before merging this. Thanks for the PR 👍

**Comment by segiddins** [comment]
@tgxworld what bundler issues?

**Comment by tgxworld** [comment]
@segiddins I've not had time to look into it yet but I'm getting the following trace.

```
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching git://github.com/collectiveidea/delayed_job_active_record.git
/root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:94:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:94:in `strip_leading_spaces'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:99:in `word_wrap'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:85:in `tell_me'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:31:in `error'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:12:in `rescue in with_friendly_errors'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
    from /root/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
    from /root/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
```

**Comment by segiddins** [comment]
Have you tried updating bundler as the warning suggests?

**Comment by tgxworld** [comment]
@segiddins Not yet will get to it soon. :)

**Comment by tgxworld** [comment]
Fixed! Turns out the docker image didn't set the right locale.

**Comment by kirs** [comment]
Thanks!

**Pull request merged**
