### PR TITLE
Add sequel scope all with default scope bench

### PR DESCRIPTION
**Pull request by bmarkons**
Sequel default scope benchmark :chart_with_upwards_trend:

### CODE REVIEW

**Comment by noahgibbs** [comment]
In general, this looks good. I don't think I see the "admin" boolean field in the schema for the pg and ActiveRecord flavors of this benchmark. Is that intentional?

**Comment by bmarkons** [comment]
Actually admin field exists in schema for ActiveRecord **default scope** benchmark. Take a look at line [#12](https://github.com/ruby-bench/ruby-bench-suite/blob/master/rails/benchmarks/bm_activerecord_scope_all_with_default_scope.rb#L12). As opposed to **scope all** benchmarks of all flavors where admin field isn't added.

Do you suggest that scope all benchmarks and default scope benchmarks should have same schemas?

**Comment by noahgibbs** [comment]
Ah, I probably read the wrong file, then. Sorry, if all the scope all benchmarks have the same schema then I was wrong. Carry on :-)

**Comment by bmarkons** [comment]
Can I merge this one? This benchmark is comparable to https://github.com/ruby-bench/ruby-bench-suite/blob/master/rails/benchmarks/bm_activerecord_scope_all_with_default_scope.rb

**Pull request merged**
