### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by bmarkons**
hey @yangshun, I emailed you to send me logos for rubybench to include in README :smile:

### CODE REVIEW

**Comment by tgxworld** [comment]
@bmarkons There are some hidden in https://github.com/ruby-bench/ruby-bench-web/tree/master/app/assets/images

**Comment by bmarkons** [comment]
oh yeah, awesome :tada:

**Comment by yangshun** [comment]
@bmarkons Do you still need them?

**Comment by bmarkons** [comment]
@yangshun these are perfect. Thanks anyway :pray:

**Comment by bmarkons** [comment]
@tgxworld I'm done, you can merge. I would like to rewrite guides a bit, but It can go in next PR :smiley:

**Pull request merged**
