### PR TITLE
Copy Railsperf benchmarks

### PR DESCRIPTION
**Pull request by kirs**
*Requires bundled Rails and sqlite3 support in the Docker machine.

### CODE REVIEW

**Comment by kirs** [comment]
I guess we need to solve #3 first.

**Comment by tgxworld** [comment]
Hey @kirs Sorry for the delay because I've been celebrating the Lunar Chinese New year here. I'll look into this soon and get back to you :smile: Thanks for porting the benchmarks over!

**Comment by tgxworld** [comment]
Closing this since the other PRs have taken care of it.

**Pull request closed without merging**
