### PR TITLE
Fix rails benchmarks

### PR DESCRIPTION
**Pull request by bmarkons**
This should fix mysql and scaffold benchmarks https://github.com/ruby-bench/ruby-bench-web/issues/193

### CODE REVIEW

**Comment by noahgibbs** [comment]
Ah, nice! So the MySQL schema define error was just an outdated mysql2 gem?

**Comment by bmarkons** [comment]
Exactly! Error is raised when activerecord tries to call `free` on `Mysql2::Result` but that method is introduced in version 0.4.3 :)

https://gemnasium.com/gems/mysql2/versions/0.4.3

**Comment by tgxworld** [comment]
Awesome thanks for fixing @bmarkons

**Comment by bmarkons** [comment]
@noahgibbs Do you think previous results should be invalidated when we change version of any dependency used? In this case mysql2.

https://github.com/ruby-bench/ruby-bench-suite/blob/master/rails/benchmarks/driver.rb#L145

^ here we generate digest and [compare it with previous](https://github.com/ruby-bench/ruby-bench-web/blob/master/app/models/benchmark_type.rb#L13) to check if benchmark file or ruby version has changed. Do you think we need to include [Gemfile](https://github.com/ruby-bench/ruby-bench-suite/blob/master/rails/Gemfile) in digest?

**Comment by SamSaffron** [comment]
Yes, totally

**Comment by noahgibbs** [comment]
I don't expect a significant performance difference between the two mysql2 gems. But I'm very willing to defer to Sam on this one. Invalidating the results *probably* doesn't matter, but if it matters, it matters a lot. So it's more conservative to re-run.

**Comment by tgxworld** [comment]
Minor versions shouldn't have much impact so I would just observe the benchmark results under the new gem and re-run if necessary. Otherwise, I'm with @noahgibbs on this to just re-run it to be conservative.

**Pull request merged**
