### PR TITLE
Add benchmark for small hash literals

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by tgxworld** [comment]
Are these benchmarks from the Ruby repo?

**Comment by krzysiek1507** [comment]
Nope. Should I add them there at first?

**Comment by tgxworld** [comment]
Yup we only run benchmarks that are listed in https://github.com/ruby/ruby/tree/trunk/benchmark as those are the ones which are important to the Ruby developers.

**Comment by krzysiek1507** [comment]
Ok! Thanks! I'll let you know if they merged or closed my PR to Ruby repo.

**Comment by krzysiek1507** [comment]
It has been merged. https://github.com/ruby/ruby/pull/2043

**Comment by tgxworld** [comment]
Nice thank you @krzysiek1507  :+1:

**Pull request merged**
